### ISSUE TITLE
Quality tools

### ISSUE THREAD

**Issue by cpmachado** [dlmarques/omenia#3]
Consider using some quality tools for your development.

List:
- linter: Check errors, and enforce quality checks - (e.g. [eslint](https://eslint.org/))
- formatter: Format your code according to a given standard - (e.g. [prettier](https://prettier.io/))
- standard editorconfig: Have standard definitions for your tools, example text editor. I tipycally use [editorconfig](https://editorconfig.org/)
- Unit testing and etc. try to find something to fit your needs.

Of note eslint and prettier need an extra package to work well together, in case you consider adopting it.

**Comment by dlmarques** [comment]
Thank you!
I will configure and apply that tools for sure!
